name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.x]

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
    
    - name: Install dependencies
      run: yarn bootstrap

    - name: Build
      run: yarn build
  
  test:
    runs-on: ubuntu-latest
    needs: build
    
    strategy:
      matrix:
        node-version: [14.17.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      
      - name: Install dependencies
        run: yarn bootstrap

      - name: Audit
        run: /bin/bash -c 'yarn audit --level high; [[ $? -ge 8 ]] && exit 1 || exit 0'

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build      
      
      - name: Unit tests
        run: yarn test
